# ===============================
# ? AUTH SERVICE CONFIG
# ===============================

spring.application.name=auth-service

server.port=${SERVER_PORT}

spring.profiles.active=${SPRING_PROFILES_ACTIVE}

# ===============================
# ? JWT CONFIG
# ===============================

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-token-expiration=${REFRESH_TOKEN_EXPIRATION}

# ===============================
# ? ACTUATOR
# ===============================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always